server:
  error:
    include-stacktrace: on_param

spring:
  config:
    activate:
      on-profile: qa

  jpa:
    show-sql: false
    hibernate:
      format_sql: false

  redis:
    host: localhost
    port: 6379
    password: ''
    ssl: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO

application:
  config:
    repository: cached-database
    cache: database

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
