server:
  error:
    include-stacktrace: never

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false
    hibernate:
      format_sql: false

  redis:
    host: localhost
    port: 6379
    password: ''
    ssl: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: INFO

application:
  config:
    repository: cached-database
    cache: database

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
