server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  profiles:
    active: memory

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: NONE

springdoc:
  swagger-ui:
    enabled: true

application:
  title: @artifactId@
  version: @version@

logging:
  level:
    root: INFO

