server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  profiles:
    active: memory

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  jpa:
    show-sql: false
    hibernate:
      format_sql: false
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: NONE

springdoc:
  api-docs:
    path: /api-docs
    enabled: false
  swagger-ui:
    enabled: false
    path: /swagger-ui.html

application:
  title: @artifactId@
  version: @version@

logging:
  level:
    root: INFO

