server:
  error:
    include-stacktrace: on_param

spring:
  config:
    activate:
      on-profile: qa

  jpa:
    show-sql: false
    hibernate:
      format_sql: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO

application:
  inject:
    event-repository: database