server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  profiles:
    active: memory
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springdoc:
  swagger-ui:
    enabled: true

application:
  title: @artifactId@
  version: @version@